
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

dynamic_padding = true

decorations = "None"

-[shell]
-program = "/bin/zsh"
-args = ["-l"]

[cursor]
style = { shape = "Underline", blinking = "Never" }

[general]
import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
]
