import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

dynamic_padding = true

decorations = "None"

[cursor]
style = { shape = "Underline", blinking = "Never" }

[shell]
program = "/bin/zsh"
args = ["-l"]
