[window]
opacity = 0.9
padding.x = 10
padding.y = 10

dynamic_padding = true
decorations = "None"

[font.normal]
family = "MesloLGS NF"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[cursor]
style = { shape = "Block", blinking = "Never" }

[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]
